services:
  api:
    build:
      context: .
      network: host
    container_name: api
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - 8000:${API_PORT}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      otel:
        condition: service_started
      osrm:
        condition: service_started
    entrypoint: ["sh", "./entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "${API_URL}/api/v1/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  db:
    image: postgres:18-alpine
    container_name: db
    networks:
      - app-network
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

  cache:
    image: redis:8.4.0-alpine
    container_name: cache
    networks:
      - app-network
    ports:
      - 6379:${CACHE_PORT}
    command: redis-server --requirepass ${CACHE_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${CACHE_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  osrm:
    image: osrm/osrm-backend:v5.25.0
    container_name: osrm
    networks:
      - app-network
    volumes:
      - ${PWD}/osrm_data:/osrm_data
    ports:
      - 5000:${OSRM_PORT}
    command: "osrm-routed --algorithm mld /osrm_data/${OSRM_MAP}.osrm"

  otel:
    image: grafana/otel-lgtm:0.16.0
    container_name: otel
    networks:
     - app-network
    ports:
      - 3000:${GRAFANA_PORT}
      - 4317:${OTLP_GRPC_PORT}

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
  osrm_data: