target-version = 'py313'
line-length = 79
exclude = [
    'app/migrations/',
    '.coveragerc'
]

[format]
quote-style = 'single'

[lint]
select = ['ALL']
ignore = [
    'B008',
    'D100',
    'D101',
    'D102',
    'D103',
    'D104',
    'D105',
    'D106',
    'D107',
    'D200',
    'D203',
    'D205',
    'D211',
    'D212',
    'D400',
    'D401',
    'D415',
    'Q000',
    'Q001',
    'Q002',
    'Q003',
    'S101',
    'COM812',
]
