services:
  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
      network: host
    networks:
      - app-network
    container_name: api
    volumes:
      - ..:/app
      - /app/.venv
    env_file:
      - ../.env
    ports:
      - 8000:${API_PORT}
    depends_on:
      db:
        condition: service_healthy
      osrm:
        condition: service_started
    command: sleep infinity
    healthcheck:
      test: ["CMD", "curl", "-f", "${API_URL}/api/v1/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  db:
    image: postgres:18-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  osrm:
    image: osrm/osrm-backend:v5.25.0
    container_name: osrm
    networks:
      - app-network
    volumes:
      - ${PWD}/osrm_data:/osrm_data
    ports:
      - 5000:${OSRM_PORT}
    command: "osrm-routed --algorithm mld /osrm_data/${OSRM_MAP}.osrm"

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  osrm_data: